services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lesson_board
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    networks:
      - default

  web:
    build: .
    image: takt2023/lesson_board
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/lesson_board
    working_dir: /lesson_board
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
