name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: |
          docker-compose up -d --build
          docker-compose exec web sleep 30 # Wait for services to be fully up

      - name: Set up the database
        run: |
          docker-compose exec web bundle exec rails db:create RAILS_ENV=test
          docker-compose exec web bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: docker-compose exec web bundle exec rspec

      - name: Run linters
        run: docker-compose exec web bundle exec rubocop
