name: CICD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start containers
        run: |
          docker-compose up -d --build
          docker-compose exec -T web sleep 30

      - name: Set up the database
        run: |
          cp config/database.yml.ci config/database.yml
          docker-compose exec -T web bundle exec rails db:create RAILS_ENV=test
          docker-compose exec -T web bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: docker-compose exec -T web bundle exec rspec

      - name: Run linters
        run: docker-compose exec -T web bundle exec rubocop

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/LessonBoard
            git pull origin HEAD
            docker-compose -f docker-compose.prod.yml up -d --build
